markdown:         kramdown
highlighter:      rouge

permalink:        pretty

title:            Jon Pitcherella
tagline:          'Developer. Home Brewer.'
description:      'Great developer.<br />Home brewer and metal head.<br />Writer of haiku.'
url:              https://jonpitcherella.com
baseurl:          /
brand-color:      '#202020'

excerpt_separator:  <!--more-->

author:
  name:           'Jon Pitcherella'
  url:            https://jonpitcherella.com

paginate:         5

plugins:          [jekyll-paginate, jekyll-gist]

social:
  email:          'jon.pitcherella@gmail.com'
  twitter:        'jonpitch'
  github:         'jonpitch'
  medium:         'jonpitch'

ga:
  id:             'UA-33882544-1'

disqus:
  shortname:      'jonpitcherella'

exclude: ['README.md', 'vendor']
