# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Jon Pitcherella
tagline:          'Developer. Home Brewer.'
description:      'Great developer.<br />Home brewer and metal head.<br />User of haiku.'
url:              http://jonpitcherella.com
baseurl:          /
brand-color:      '#202020'

author:
  name:           'Jon Pitcherella'
  url:            http://jonpitcherella.com

paginate:         5

# Gems
gems:             [jekyll-paginate, jekyll-gist]

# Social
social:
  email:          'jon.pitcherella@gmail.com'
  twitter:        'jonpitch'
  github:         'jonpitch'
  medium:         'jonpitch'

# Google Analytics
ga:
  id:             'UA-33882544-1'

# Disqus
disqus:
  shortname:      'jonpitcherella'

# Build Settings
exclude: ['README.md']
