baseURL = 'https://jonpitcherella.com/'
languageCode = 'en-US'
title = 'Jon Pitcherella'
copyright = 'copyright Jon Pitcherella {year}'
googleAnalytics = 'UA-33882544-1'
enableRobotsTXT = true

[Params]
    description = 'pretty ok software engineer | triathlete | heavy metal enthusiast | home brewer | he/him | black lives matter'